### ISSUE TITLE
BUG: swagger json incorrectly structures 'required' on body schemas

### ISSUE THREAD

**Issue by thomasmost** [Cody2333/koa-swagger-decorator#109]
Body schemas are not converted to json in a valid Swagger 2.0 structure

This code:

```ts

  @AppointmentTag
  @request('post', '/example')
  @summary('demonstrate incorrect body structure')
  @body({
    prop1: {
      type: 'string',
      required: true,
      description: 'The first required prop',
    },
    prop2: {
      type: 'string',
      required: true,
      description: 'The second required prop',
    },
    prop3: {
      type: 'string',
      required: false,
      description: 'An optional prop',
    },
  })
  public static async foo(ctx: TeddyRequestContext) {
    ctx.status = 204;
  }
```

...generates the following json:

```json

    "/api/appointment/example": {
      "post": {
        "summary": "demonstrate incorrect body structure",
        "description": "demonstrate incorrect body structure",
        "parameters": [
          {
            "name": "data",
            "description": "request body",
            "schema": {
              "type": "object",
              "properties": {
                "prop1": {
                  "type": "string",
                  "required": true,
                  "description": "The first required prop"
                },
                "prop2": {
                  "type": "string",
                  "required": true,
                  "description": "The second required prop"
                },
                "prop3": {
                  "type": "string",
                  "required": false,
                  "description": "An optional prop"
                }
              }
            },
            "in": "body"
          }
        ],
        "responses": { "200": { "description": "success" } },
        "tags": ["appointments"],
        "security": [{ "ApiKeyAuth": [] }]
      }
    },
```

...which results in the following errors in the Swagger Editor (editor.swagger.io)

```
Structural error at paths./api/appointment/example.post.parameters.0.schema.properties.prop1.required
should be array
Structural error at paths./api/appointment/example.post.parameters.0.schema.properties.prop2.required
should be array
Structural error at paths./api/appointment/example.post.parameters.0.schema.properties.prop3.required
should be array
```

I believe the YAML should look like **this, instead:**

```yml
  /api/appointment/example:
    post:
      summary: demonstrate incorrect body structure
      description: demonstrate incorrect body structure
      parameters:
        - name: data
          description: request body
          schema:
            type: object
            required:
              - prop1
              - prop2
            properties:
              prop1:
                type: string
                description: The first required prop
              prop2:
                type: string
                description: The second required prop
              prop3:
                type: string
                description: An optional prop
          in: body
```

...or, in JSON:

```json

    "/api/appointment/example": {
      "post": {
        "summary": "demonstrate incorrect body structure",
        "description": "demonstrate incorrect body structure",
        "parameters": [
          {
            "name": "data",
            "description": "request body",
            "schema": {
              "type": "object",
              "required": [
                "prop1",
                "prop2" 
              ],
              "properties": {
                "prop1": {
                  "type": "string",
                  "description": "The first required prop"
                },
                "prop2": {
                  "type": "string",
                  "description": "The second required prop"
                },
                "prop3": {
                  "type": "string",
                  "description": "An optional prop"
                }
              }
            },
            "in": "body"
          }
        ],
        "responses": { "200": { "description": "success" } },
        "tags": ["appointments"],
        "security": [{ "ApiKeyAuth": [] }]
      }
    },
```
